### ISSUE TITLE
Setting site wide, or retrofitting to all active events, or setting on Templates

### ISSUE THREAD

**Issue by petednz** [pradpnayak/skipeventconfirmpage#3]
Hi - thanks for this - just giving it a try out

Looks like it is built to be event specific - or perhaps i am overlooking something

1/ is there a way to set this site-wide for all future events

2/ is there a way eg API Explorer, to set this for all current events, so that if they get copied the setting is already in place

3/ is there a way of setting this on Event Templates - I could not see the setting there

**Comment by petednz** [comment]
I think we have sorted 1/. We did 2/ via sql. not sure 3/ matters after we did 2/

**Comment by pradpnayak** [comment]
Hi @petednz 

> 1/ is there a way to set this site-wide for all future events
> 

Yes

> 2/ is there a way eg API Explorer, to set this for all current events, so that if they get copied the setting is already in place
> 

Yes, via SQL or API4

> 3/ is there a way of setting this on Event Templates - I could not see the setting there

Via API4 yes
