### ISSUE TITLE
PHP 8.1 Compatibility?

### ISSUE THREAD

**Issue by themak1985** [pradpnayak/skipeventconfirmpage#4]
Just upgraded our site from 7.4 to 8.1 and a handful of extensions had some issues. This was one of them: Anytime I try to enable the extension, i get a wordpress fatal error:

PHP Fatal error:  Array and string offset access syntax with curly braces is no longer supported in /home/example/www/www/wp-content/uploads/civicrm/ext/skipeventconfirmpage/skipeventconfirmpage.civix.php on line 246

Possible to fix?

**Comment by pradpnayak** [comment]
Fixed and released a new https://github.com/pradpnayak/skipeventconfirmpage/releases/tag/v1.1
